#!/usr/bin/env python3
"""Planes de estudio cargados a mano (transcriptos de PDFs escaneados/PNGs).

Origen persistente: se corre DESPUES de los scrapers y de planes_pdf.py,
antes de unir_todo.py. Idempotente: solo completa carreras sin plan.

Uso: python3 scrapers/planes_manual.py [--dry]
"""
import json
import os
import sys

DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")

PLANES = {
    "ies9009.json": {
        "Tecnicatura Superior en Administración de Empresas": [
            {"anio": "1º año", "materias": [
                "Informática y Tecnología I (Taller)",
                "Inglés (Módulo)",
                "Administración (Módulo)",
                "Contabilidad (Módulo)",
                "Microeconomía (Módulo)",
                "Matemática (Módulo)",
                "Estadística (Módulo)",
                "Comunicación, comprensión y producción de Textos (Taller)",
                "Oratoria (Taller)",
                "Práctica Profesionalizante I (Taller)",
            ]},
            {"anio": "2º año", "materias": [
                "Informática y Tecnología II (Taller)",
                "Inglés Técnico (Taller)",
                "Macroeconomía (Módulo)",
                "Comercialización (Módulo)",
                "Estructura de Costos (Módulo)",
                "Desarrollo Territorial (Taller)",
                "Cálculo Financiero (Módulo)",
                "Introducción al Derecho (Módulo)",
                "Problemática Sociocultural y del Trabajo (Módulo)",
                "Gestión Financiera (Módulo)",
                "Derecho de la Empresa (Módulo)",
                "Práctica Profesionalizante II",
            ]},
            {"anio": "3º año", "materias": [
                "Formulación y Evaluación de Proyectos (Taller)",
                "Producto y Servicio (Módulo)",
                "Habilidades Interpersonales (Taller)",
                "Ética Profesional (Módulo)",
                "Control de Gestión (Módulo)",
                "Derecho Laboral (Módulo)",
                "Gestión de la Calidad (Módulo)",
                "Logística Integral (Módulo)",
                "Creatividad e Innovación (Taller)",
                "Psicología Organizacional (Módulo)",
                "Práctica Impositiva y de Liquidación de Sueldos (Taller)",
                "Administración de Personal (Módulo)",
                "Práctica Profesionalizante III",
            ]},
        ],
        "Tecnicatura en Diseño Gráfico": [
            {"anio": "1º año", "materias": [
                "Diseño en Comunicación Visual I",
                "Técnicas de Representación I",
                "Herramientas Digitales I",
                "Historia del Arte y del Diseño I",
                "Inglés Técnico",
                "Tipografía I",
                "Problemática Sociocultural y el Contexto",
                "Percepción Visual",
                "Prácticas de Lectura, Escritura y Oralidad",
                "Publicidad I",
                "Práctica Profesionalizante I",
            ]},
            {"anio": "2º año", "materias": [
                "Diseño en Comunicación Visual II",
                "Técnicas de Representación II",
                "Herramientas Digitales II",
                "Fotografía",
                "Historia del Arte y del Diseño II",
                "Semiología",
                "Tipografía II",
                "Tecnología Gráfica I",
                "Tecnología Gráfica II",
                "Práctica Profesionalizante II",
            ]},
            {"anio": "3º año", "materias": [
                "Diseño en Comunicación Visual III",
                "Técnicas de Representación III",
                "Herramientas Digitales III",
                "Comunicación, Medios y Nuevas Tecnologías",
                "Ética Profesional",
                "Mercadotecnia para Pymes",
                "Formulación y Evaluación de Proyectos",
                "Gestión de Microemprendimientos",
                "Metodología de la Investigación",
                "Producción del Diseño Regional",
                "Práctica Profesionalizante III",
            ]},
        ],
        "Tecnicatura en Guía de Turismo": [
            {"anio": "1º año", "materias": [
                "Taller de Oratoria y Comunicación",
                "Taller de Competencias Digitales",
                "Gestión de Riesgos y Primeros Auxilios",
                "Introducción al Turismo",
                "Inglés I",
                "Procesos Históricos y Patrimonio Cultural de Mendoza",
                "Portugués I",
                "Dinámica para la Recreación Grupal",
                "Enoturismo",
                "Espacios Turísticos de Mendoza",
                "Práctica Profesionalizante I",
            ]},
            {"anio": "2º año", "materias": [
                "Inglés II",
                "Portugués II",
                "Derecho y Ética para la Gestión del Turismo",
                "Técnicas de Guiado y Coordinación Turística",
                "Electiva (Arte y Cultura / Campamentismo - Senderismo)",
                "Espacios Turísticos de Argentina",
                "Prestación de Servicios Turísticos",
                "Espacios Turísticos Mundiales",
                "Guía de Sitio de Áreas Naturales Protegidas",
                "Práctica Profesionalizante II",
            ]},
        ],
        "Tecnicatura en Gestión de Alojamientos Turísticos": [
            {"anio": "1º año", "materias": [
                "Taller de Oratoria y Comunicación",
                "Taller de Competencias Digitales",
                "Seguridad, Higiene y Mantenimiento",
                "Introducción a los Alojamientos Turísticos",
                "Inglés I",
                "Procesos Históricos y Patrimonio Cultural de Mendoza",
                "Portugués I",
                "Protocolo y Ceremonial",
                "Administración de Pisos",
                "Estudio del espacio turístico de Mendoza y Argentina",
                "Práctica Profesionalizante I",
            ]},
            {"anio": "2º año", "materias": [
                "Inglés II",
                "Portugués II",
                "Derecho y Ética para la Gestión de Alojamientos Turísticos",
                "Consejería y Recepción",
                "Dirección y Gestión de empresas prestadoras del servicio de alojamiento turístico",
                "Organización de Eventos y Convenciones",
                "Gestión del personal de alojamiento",
                "Estadística aplicada a los alojamientos",
                "Comercialización de servicios de alojamientos turísticos",
                "Práctica Profesionalizante II",
            ]},
        ],
    },
    "ies9003.json": {
        "Profesorado de Educación Inicial": [
            {"anio": "1º año", "materias": [
                "Pensamiento Filosófico",
                "Sistema Educativo (Anual)",
                "Comprensión y Producción de Textos Académicos (Anual)",
                "Centralidad del Juego",
                "Lenguajes Artísticos Expresivos - Teatro (Anual)",
                "Lenguajes Artísticos Expresivos - Música (Anual)",
                "PPD I (Anual)",
                "Pedagogía",
                "Juego y Producción de Objetos Lúdicos",
            ]},
            {"anio": "2º año", "materias": [
                "Didáctica",
                "Instituciones Educativas",
                "Prácticas Lingüísticas en Educación Inicial (Anual)",
                "Lenguajes Artísticos Expresivos - Artes Visuales (Anual)",
                "Educación Matemática Temprana e Inicial I (Anual)",
                "Sujetos de la Educación (Anual)",
                "PPD II (Anual)",
                "Psicología Educacional",
                "Educación y Atención Temprana al Desarrollo Infantil",
                "Didáctica de Jardín Maternal",
            ]},
            {"anio": "3º año", "materias": [
                "Gestión y Evaluación de los Aprendizajes",
                "Literatura Infantil",
                "Didáctica de Jardín de Infantes",
                "Alfabetización Temprana e Inicial (Anual)",
                "Didáctica del Ambiente Natural (Anual)",
                "Didáctica del Ambiente Social (Anual)",
                "Motricidad en Jardín Maternal y en Jardín de Infantes (Anual)",
                "PPD III (Anual)",
                "Proyectos de Intervención Socioeducativa",
                "Educación en la Diversidad",
                "Educación Matemática Inicial II",
            ]},
            {"anio": "4º año", "materias": [
                "ESI",
                "Educación y Tecnologías Digitales",
                "Problemáticas de la Educación Inicial",
                "Salud y Cultura del Cuidado",
                "PPD IV (Anual)",
                "Historia y Patrimonio Cultural de Mendoza",
                "Formación Complementaria General",
                "Formación Complementaria Específica",
                "Formación Ética y Ciudadana y su Didáctica",
            ]},
        ],
    },
    "ies9008.json": {
        "Técnico Superior en IA y Ciencia de Datos": [
            {"anio": "1º año", "materias": [
                "Programación I",
                "Matemática Aplicada",
                "Lógica Computacional",
                "Inglés Técnico I",
                "Alfabetización Académica",
                "Arquitectura de Dispositivos",
                "Base de Datos I",
                "Práctica Profesionalizante I",
                "Seminario Nuevas Tecnologías",
                "Sistemas Operativos I",
            ]},
            {"anio": "2º año", "materias": [
                "Programación Orientada al Análisis de Datos",
                "Matemática Aplicada a la Ciencia de Datos",
                "Estadística y Probabilidades para Gestión de Datos",
                "Ciencia de Datos y Datos Masivos",
                "Inglés Técnico II",
                "Gestión de Proyectos",
                "Comunicación de Resultados Analíticos",
                "Minería de Datos",
                "Práctica Profesionalizante II",
                "Metodologías Ágiles",
                "Ética y Legislación en el Tratamiento de Datos",
            ]},
            {"anio": "3º año", "materias": [
                "IA Aplicada al Procesamiento del Lenguaje Natural",
                "IA Aplicada al Procesamiento Digital de Imágenes",
                "Inglés Técnico III",
                "Matemática Aplicada a la IA",
                "Redes Neuronales y Aprendizaje Automático",
                "Seminario de Actualización",
                "Sistemas de Inteligencia Artificial",
                "Prompts para Inteligencia Artificial",
                "Inteligencia Artificial Generativa",
                "Fundamentos de Ciberseguridad",
                "Grandes Modelos del Lenguaje",
                "Práctica Profesionalizante III",
            ]},
        ],
        "Tecnicatura Superior en Desarrollo de Software": [
            {"anio": "1º año", "materias": [
                "Programación I",
                "Matemática Aplicada",
                "Lógica Computacional",
                "Inglés Técnico I",
                "Alfabetización Académica",
                "Arquitectura de Dispositivos",
                "Seminario Nuevas Tecnologías",
                "Sistemas Operativos I",
                "Base de Datos I",
                "Práctica Profesionalizante I",
            ]},
            {"anio": "2º año", "materias": [
                "Programación II",
                "Matemática Discreta",
                "Administración de Servidores",
                "Inglés Técnico II",
                "Comunicación y Redes",
                "Modelado de Software",
                "Sistemas Operativos II",
                "Análisis Matemático",
                "Base de Datos II",
                "Práctica Profesionalizante II",
            ]},
            {"anio": "3º año", "materias": [
                "Programación III",
                "Arquitectura y Diseño de Interfaces: UI y UX",
                "Auditoría y Calidad de Sistema",
                "Inglés Técnico III",
                "Gestión de Proyectos de Software",
                "Base de Datos III",
                "Legislación Informática y Ética Profesional",
                "Estadística y Probabilidades para el Desarrollo de Software",
                "Ciberseguridad",
                "Metodologías Ágiles",
                "Práctica Profesionalizante III",
            ]},
        ],
    },
    "ies9004.json": {
        "Profesorado de Educación Inicial": [
            {"anio": "1º año", "materias": [
                "Pensamiento Filosófico",
                "Sistema Educativo",
                "Comprensión y Producción de Textos Académicos",
                "Pedagogía",
                "Centralidad del Juego",
                "Juego y Producción de Objetos Lúdicos",
                "Lenguajes Artísticos Expresivos - Teatro",
                "Lenguajes Artísticos Expresivos - Música",
                "Práctica Profesional Docente I",
            ]},
            {"anio": "2º año", "materias": [
                "Didáctica",
                "Instituciones Educativas",
                "Psicología Educacional",
                "Educación y Atención Temprana al Desarrollo Infantil",
                "Didáctica del Jardín Maternal",
                "Prácticas Lingüísticas en Ed. Inicial",
                "Lenguajes Artísticos Expresivos - Artes Visuales",
                "Educación Matemática Temprana e Inicial I",
                "Sujetos de la Educación",
                "Práctica Profesional Docente II",
            ]},
            {"anio": "3º año", "materias": [
                "Gestión y Evaluación de los Aprendizajes",
                "Proyectos de Intervención Socioeducativa",
                "Educación en la Diversidad",
                "Literatura Infantil",
                "Didáctica de Jardín de Infantes",
                "Educación Matemática Inicial II",
                "Alfabetización Temprana e Inicial",
                "Didáctica del Ambiente Natural",
                "Didáctica del Ambiente Social",
                "Motricidad en Jardín Maternal y en Jardín de Infantes",
                "Práctica Profesional Docente III",
            ]},
            {"anio": "4º año", "materias": [
                "Educación Sexual Integral",
                "Educación y Tecnologías Digitales",
                "Historia y Patrimonio Cultural de Mendoza",
                "Formación Complementaria General",
                "Problemáticas de la Ed. Inicial",
                "Salud y Cultura del Cuidado",
                "Formación Ética y Ciudadana y su Didáctica",
                "Formación Complementaria Específica",
                "Práctica Profesional Docente IV",
            ]},
        ],
        "Profesorado Educación Primaria": [
            {"anio": "1º año", "materias": [
                "Pensamiento Filosófico",
                "Comprensión y Producción de Textos Académicos",
                "Sistema Educativo",
                "Pedagogía",
                "Numeración",
                "Lengua y Literatura Infantil y Juvenil",
                "Educación Artística",
                "Práctica Profesional Docente I",
                "Didáctica",
                "Psicología Educacional",
                "Instituciones Educativas",
            ]},
            {"anio": "2º año", "materias": [
                "Didáctica",
                "Psicología Educacional",
                "Instituciones Educativas",
                "Sujetos de la Educación",
                "Números Racionales y su Didáctica",
                "Cs. Sociales y su Didáctica I",
                "Cs. Naturales y su Didáctica I",
                "Lengua y su Didáctica",
                "Literatura Infantil y Juvenil y su Didáctica",
                "Espacio, Geometría y su Didáctica",
                "Práctica Profesional Docente II",
            ]},
            {"anio": "3º año", "materias": [
                "Gestión y Evaluación de los Aprendizajes",
                "Proyectos de Intervención Estratégica",
                "Educación en la Diversidad",
                "Educación Tecnológica",
                "Medida y su Didáctica",
                "Cs. Sociales y su Didáctica II",
                "Cs. Naturales y su Didáctica II",
                "Alfabetización",
                "Formación Ética y Ciudadana y su Didáctica",
                "Álgebra, Funciones y su Didáctica",
                "Práctica Profesional Docente III",
            ]},
            {"anio": "4º año", "materias": [
                "Educación Sexual Integral",
                "Educación y Tecnologías Digitales",
                "Historia y Patrimonio Cultural de Mendoza",
                "Formación Complementaria General",
                "Didáctica de la Lengua y de la Literatura Infantil y Juvenil",
                "Didáctica de la Matemática",
                "Didáctica de las Ciencias Sociales",
                "Didáctica de las Ciencias Naturales",
                "Formación Complementaria II",
                "Práctica Profesional Docente IV",
            ]},
        ],
        "Profesorado de Geografía": [
            {"anio": "1º año", "materias": [
                "Geografía de la Población",
                "Geografía de los Sistemas Ambientales",
                "Geografía de Mendoza",
                "Sociedad, Cultura y Territorio",
                "Técnicas de Trabajo en Geografía I",
                "Didáctica General",
                "Pedagogía",
                "Promoción de la Salud",
                "Prácticas de la Lectura / Escritura y Oralidad",
                "Tecnologías de la Comunicación y la Información",
                "Práctica Profesional Docente",
            ]},
            {"anio": "2º año", "materias": [
                "Apropiación de los Recursos Naturales",
                "Economía, Estado y Territorio",
                "Geografía de la Argentina",
                "Problemática Ambiental",
                "Técnicas de Trabajo en Geografía II",
                "Filosofía, Historia y Política de la Educación Argentina",
                "Psicología Educacional",
                "Práctica Profesional Docente II",
                "Historia Política, Social, Cultural y Económica de Argentina",
                "Sujeto de Educación",
                "Instituciones Educativas",
                "UDI: Importancia de la Lectura N.S. Emociones, Motivación",
            ]},
            {"anio": "3º año", "materias": [
                "Didáctica de la Geografía I",
                "Epistemología de la Geografía",
                "Geografía de América Latina",
                "Geografía de la Mundialización",
                "Geografía de los Espacios Rurales",
                "Geografía de los Espacios Urbanos",
                "TICs Aplicadas a la Enseñanza de la Geografía",
                "Práctica Profesional Docente III",
                "UDI: Geografía de los Riesgos Naturales",
                "Historia Política, Social, Económica y Cultural de América Latina",
                "Sociología de la Educación",
            ]},
            {"anio": "4º año", "materias": [
                "Didáctica de la Geografía II",
                "Educación Ambiental",
                "Geopolítica de los Espacios Mundiales",
                "Investigación Geográfica",
                "Práctica Profesional Docente IV",
            ]},
        ],
        "Tecnicatura Superior en Acompañamiento Terapéutico": [
            {"anio": "1º año", "materias": [
                "Problemáticas de la Educación Argentina",
                "Psicología General y del Desarrollo",
                "Fundamentos de Acompañamiento Terapéutico",
                "Salud Pública y Salud Mental",
                "Psicopatología",
                "Filosofía",
                "Taller de Comunicación Oral y Escrita",
                "Taller de Práctica Profesionalizante I",
            ]},
            {"anio": "2º año", "materias": [
                "Ética y Deontología Profesional",
                "Metodología de la Investigación",
                "Psicología Evolutiva",
                "Psicología Social y Comunitaria",
                "Didáctica y Estrategias de Intervención",
                "Acompañamiento Terapéutico en Discapacidad",
                "Acompañamiento Terapéutico en Salud Mental",
                "Taller de Práctica Profesionalizante II",
            ]},
            {"anio": "3º año", "materias": [
                "Políticas Públicas y Legislación",
                "Acompañamiento Terapéutico en Infancia y Adolescencia",
                "Acompañamiento Terapéutico en Adultos y Adultos Mayores",
                "Acompañamiento Terapéutico en Consumos Problemáticos",
                "Investigación Educativa",
                "Taller de Integración y Síntesis Final",
                "Taller de Práctica Profesionalizante III",
            ]},
        ],
    },
    "ies9005.json": {
        "Profesorado de Educación Primaria": [
            {"anio": "1º año", "materias": [
                "Pensamiento Filosófico",
                "Sistema Educativo",
                "Comprensión y Producción de Textos Académicos",
                "Pedagogía",
                "Educación Artística",
                "Lengua y Literatura Infantil y Juvenil",
                "Numeración",
                "Práctica Profesional Docente I",
            ]},
            {"anio": "2º año", "materias": [
                "Didáctica",
                "Instituciones Educativas",
                "Sujetos de la Educación",
                "Psicología Educacional",
                "Ciencias Sociales y su Didáctica I",
                "Números Racionales y su Didáctica",
                "Espacio, Geometría y su Didáctica",
                "Ciencias Naturales y su Didáctica I",
                "Lengua y su Didáctica",
                "Literatura Infantil y Juvenil y su Didáctica",
                "Práctica Profesional Docente II",
            ]},
            {"anio": "3º año", "materias": [
                "Gestión y Evaluación de los Aprendizajes",
                "Formación Ética y Ciudadana y su Didáctica",
                "Proyectos de Intervención Estratégica",
                "Educación Tecnológica",
                "Educación en la Diversidad",
                "Medida y su Didáctica",
                "Álgebra, Funciones y su Didáctica",
                "Ciencias Sociales y su Didáctica II",
                "Ciencias Naturales y su Didáctica II",
                "Alfabetización",
                "Práctica Profesional Docente III",
            ]},
            {"anio": "4º año", "materias": [
                "ESI",
                "Educación y Tecnologías Digitales",
                "Didáctica de la Lengua y la Literatura Infantil y Juvenil",
                "Didáctica de la Matemática",
                "Didáctica de las Ciencias Sociales",
                "Didáctica de las Ciencias Naturales",
                "Historia y Patrimonio Cultural de Mendoza",
                "Formación Complementaria General",
                "Formación Complementaria Específica",
                "Práctica Profesional Docente IV",
            ]},
        ],
    },
    "ies9016.json": {
        "Profesorado de Educación Física": [
            {"anio": "1º año", "materias": [
                "Actualización Formativa",
                "Prácticas de Lectura, Escritura y Oralidad",
                "Tecnologías de la Información y la Comunicación",
                "Historia Política, Social, Económica y Cultural de América Latina",
                "Pedagogía",
                "Didáctica General",
                "Fundamentos de la Motricidad",
                "Anatomía Funcional",
                "Juego Motor",
                "Expresión y Comunicación Motriz",
                "Deporte Psicomotriz I",
                "Deporte Sociomotriz I",
                "Práctica Profesional I",
            ]},
            {"anio": "2º año", "materias": [
                "Psicología Educacional",
                "Historia y Política de la Educación Argentina",
                "Instituciones Educativas",
                "Sujeto de las Acciones Motrices y su Aprendizaje",
                "Sujeto de las Acciones Motrices y su Contexto",
                "Fisiología de la Actividad Física",
                "Vida en la Naturaleza y Acciones Motrices",
                "Deporte Psicomotriz II",
                "Deporte Sociomotriz II",
                "Práctica Profesional II",
            ]},
            {"anio": "3º año", "materias": [
                "Sociología de la Educación",
                "Filosofía",
                "Didáctica de la Educación Física para el Nivel Inicial y Primario",
                "Didáctica de la Educación Física para el Nivel Secundario",
                "Actividad Física para la Salud",
                "Actividad Física para la Socio Recreación",
                "Deporte Espacio Separado",
                "Deporte Espacio Común",
                "Práctica Profesional III",
            ]},
            {"anio": "4º año", "materias": [
                "Ética Profesional y Práctica Docente",
                "Educación Física para la Atención de Necesidades Educativas Especiales",
                "Gestión de Proyectos de Actividades Físicas y Deportes",
                "Dirección Técnica de Gimnasios",
                "TIC Orientada",
                "Opción Institucional I",
                "Opción Institucional II",
                "Práctica Profesional IV",
            ]},
        ],
    },
}


def main():
    dry = "--dry" in sys.argv
    total = 0
    for fname, carreras in PLANES.items():
        path = os.path.join(DATA, fname)
        if not os.path.exists(path):
            print(f"!! no existe {fname}")
            continue
        with open(path, encoding="utf-8") as f:
            doc = json.load(f)
        asignadas = 0
        for inst in doc["instituciones"]:
            for c in inst.get("carreras", []):
                nombre = c["nombre_carrera"]
                if nombre in carreras and not c.get("plan_estudio"):
                    c["plan_estudio"] = carreras[nombre]
                    asignadas += 1
                    n = sum(len(a["materias"]) for a in carreras[nombre])
                    print(f"   OK  {nombre[:52]:54} {len(carreras[nombre])}a/{n}m")
        for nombre in carreras:
            found = any(nombre == c["nombre_carrera"]
                        for i in doc["instituciones"] for c in i.get("carreras", []))
            if not found:
                print(f"   ?? carrera no encontrada: {nombre}")
        if asignadas and not dry:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(doc, f, ensure_ascii=False, indent=2)
                f.write("\n")
        total += asignadas
        print(f"### {fname} — {asignadas} asignadas{'  (DRY RUN)' if dry else ''}")
    print(f"\nTotal: {total} planes manuales aplicados")


if __name__ == "__main__":
    main()
