#!/usr/bin/env python3
"""Planes de estudio de IES 9-002 Tomás Godoy Cruz (transcriptos a mano).

Se corre después de los scrapers y antes de unir_todo.py. Idempotente: solo
completa carreras sin plan.

Uso: python3 scrapers/planes_godoycruz.py [--dry]
"""
import json
import os
import sys

DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")

PLANES = {
    "Profesorado de Educación Especial": [
        {"anio": "1º año", "materias": [
            "Comprensión y Producción de Textos Académicos",
            "Pensamiento Filosófico",
            "Pedagogía",
            "Sistema Educativo",
            "Educación Artística: Artes Visuales",
            "Educación Artística: Música",
            "Educación Especial Contemporánea",
            "Neuropsicosociología del Desarrollo",
            "Discapacidad Intelectual: características del desarrollo",
            "Atención Temprana",
            "Práctica Profesional Docente I",
        ]},
        {"anio": "2º año", "materias": [
            "Didáctica",
            "Psicología Educacional",
            "Instituciones Educativas",
            "Abordaje Pedagógico Didáctico I",
            "Sujetos de la Educación I",
            "Sujetos de la Educación II",
            "Psicomotricidad",
            "Discapacidad Motora y Abordaje Pedagógico Didáctico",
            "Didáctica de la Matemática",
            "Didáctica de la Lengua",
            "Didáctica de la Literatura",
            "Didáctica de las Ciencias Naturales",
            "Práctica Profesional Docente II",
        ]},
        {"anio": "3º año", "materias": [
            "Gestión y Evaluación de los Aprendizajes",
            "Proyectos de Intervención Socioeducativa",
            "Didáctica de la Formación Ética y Ciudadana",
            "Abordaje Pedagógico Didáctico II",
            "Comunicación y Desarrollo del Lenguaje en la Persona con Discapacidad",
            "Didáctica de las Ciencias Sociales",
            "Discapacidad Múltiple y Abordaje Pedagógico Didáctico",
            "Perspectiva Social, Transición a la Vida Adulta y Ocupación Laboral",
            "Alfabetización",
            "Práctica Profesional Docente III",
        ]},
        {"anio": "4º año", "materias": [
            "UCE Formación Complementaria General",
            "Educación y Tecnologías Digitales",
            "UCE Formación Complementaria Específica",
            "Educación Sexual Integral",
            "Historia y Patrimonio Cultural de Mendoza",
            "Educación Artística: Teatro",
            "Práctica Profesional Docente IV",
        ]},
    ],
    "Profesorado de Educación Secundaria en Física": [
        {"anio": "1º año", "materias": [
            "Física I",
            "Álgebra y Geometría Analítica",
            "Laboratorio de Física",
            "Química I",
            "Cálculo I",
            "Pedagogía",
            "Comprensión y Producción de Textos Académicos",
            "Formación Práctica Profesional I",
        ]},
        {"anio": "2º año", "materias": [
            "Física II",
            "Cálculo II",
            "Didáctica de la Física I",
            "Historia de la Física",
            "Sujeto de la Educación",
            "Formación Complementaria Específica",
            "Oscilaciones y Ondas Mecánicas",
            "Didáctica General",
            "Pensamiento Filosófico",
            "Sistema Educativo",
            "Formación Práctica Profesional II",
        ]},
        {"anio": "3º año", "materias": [
            "Física III",
            "Probabilidad y Estadística",
            "Didáctica de la Física II",
            "Cálculo III",
            "Química II",
            "Óptica",
            "Física Experimental",
            "Educación para la Diversidad",
            "Gestión y Evaluación de los Aprendizajes",
            "Formación Práctica Profesional III",
        ]},
        {"anio": "4º año", "materias": [
            "Física IV",
            "Fisicoquímica",
            "Fundamentos de Astronomía",
            "Mecánica Analítica",
            "Epistemología de la Física",
            "UDJE Historia y Patrimonio de Mendoza",
            "Educación y Tecnologías Digitales",
            "Educación Sexual Integral",
            "Formación Práctica Profesional IV",
        ]},
    ],
    "Profesorado de Educación Inicial": [
        {"anio": "1º año", "materias": [
            "Pensamiento Filosófico",
            "Pedagogía",
            "Sistema Educativo",
            "Comprensión y Producción de Textos Académicos",
            "Centralidad del Juego",
            "Juego y Producción de Objetos Lúdicos",
            "Lenguajes Artísticos Expresivos - Teatro",
            "Lenguajes Artísticos Expresivos - Música",
            "Práctica Profesional Docente I",
        ]},
        {"anio": "2º año", "materias": [
            "Didáctica",
            "Psicología Educacional",
            "Instituciones Educativas",
            "Educación y Atención Temprana al Desarrollo Infantil",
            "Didáctica de Jardín Maternal",
            "Didáctica de Jardín de Infantes",
            "Prácticas Lingüísticas en Educación Inicial",
            "Lenguajes Artísticos Expresivos - Artes Visuales",
            "Educación Matemática Temprana e Inicial I",
            "Sujetos de la Educación",
            "Motricidad en Jardín Maternal y en Jardín de Infantes",
            "Práctica Profesional Docente II",
        ]},
        {"anio": "3º año", "materias": [
            "Gestión y Evaluación de los Aprendizajes",
            "Proyectos de Intervención Socioeducativa",
            "Literatura Infantil",
            "Educación en la Diversidad",
            "Educación Matemática Inicial II",
            "Alfabetización Temprana e Inicial",
            "Didáctica del Ambiente Natural",
            "Didáctica del Ambiente Social",
            "Práctica Profesional Docente III",
        ]},
        {"anio": "4º año", "materias": [
            "Educación Sexual Integral",
            "Educación y Tecnologías Digitales",
            "Historia y Patrimonio Cultural de Mendoza",
            "Problemáticas de la Educación Inicial",
            "Formación Complementaria General",
            "Formación Complementaria Específica",
            "Salud y Cultura del Cuidado",
            "Formación Ética y Ciudadana y su Didáctica",
            "Práctica Profesional Docente IV",
        ]},
    ],
    "Profesorado de Educación Secundaria en Lengua y Literatura": [
        {"anio": "1º año", "materias": [
            "Pensamiento Filosófico",
            "Pedagogía",
            "Sistema Educativo",
            "Comprensión y Producción de Textos Académicos",
            "Literatura Universal I",
            "Literatura y Cultura Grecolatina",
            "Morfología y Semántica Léxica",
            "Fundamentos de la Lengua",
            "Fundamentos de la Literatura",
            "Práctica Profesional Docente I",
        ]},
        {"anio": "2º año", "materias": [
            "Instituciones Educativas",
            "Didáctica",
            "Sujeto de la Educación",
            "Psicología Educacional",
            "Literatura Universal II",
            "Literatura Latinoamericana I",
            "Sintaxis y Semántica Proposicional",
            "Fonética, Fonología y Grafemática",
            "Lingüística del Texto y Análisis del Discurso I",
            "Literatura Española",
            "Práctica Profesional Docente II",
        ]},
        {"anio": "3º año", "materias": [
            "Gestión y Evaluación de los Aprendizajes",
            "Proyectos de Intervención Estratégica",
            "Educación en la Diversidad",
            "Literatura Argentina I",
            "Literatura Latinoamericana II",
            "Alfabetización",
            "Lingüística del Texto y Análisis del Discurso II",
            "Didáctica de la Lengua",
            "Didáctica de la Literatura",
            "Práctica Profesional Docente III",
        ]},
        {"anio": "4º año", "materias": [
            "Educación y Tecnologías Digitales",
            "Educación Sexual Integral",
            "Historia y Patrimonio Cultural de Mendoza",
            "UDJE Formación Complementaria General",
            "UDJE Formación Complementaria Específica",
            "Literatura Argentina II",
            "Teoría y Crítica Literaria",
            "Filología",
            "Práctica Profesional Docente IV",
        ]},
    ],
    "Profesorado de Educación Secundaria en Matemática": [
        {"anio": "1º año", "materias": [
            "Álgebra I",
            "Cálculo I",
            "Geometría I",
            "Geometría Analítica",
            "Promoción de la Salud",
            "Historia Política, Social, Económica y Cultural de América Latina",
            "Prácticas de Lectura, Escritura y Oralidad",
            "Tecnologías de la Comunicación y la Información",
            "Pedagogía",
            "Didáctica General",
            "Práctica Profesional Docente I",
        ]},
        {"anio": "2º año", "materias": [
            "Álgebra II",
            "Cálculo II",
            "Geometría II",
            "Probabilidad y Estadística I",
            "Didáctica de la Matemática I",
            "Psicología Educacional",
            "Sujetos de la Educación",
            "Historia y Política de la Educación Argentina",
            "Instituciones Educativas",
            "Práctica Profesional Docente II",
        ]},
        {"anio": "3º año", "materias": [
            "Historia de la Matemática",
            "Las TIC en la Enseñanza de la Matemática",
            "Geometría III",
            "Probabilidad y Estadística II",
            "Didáctica de la Matemática II",
            "Álgebra III",
            "Física I",
            "UDI - CFE",
            "Epistemología de la Matemática",
            "Filosofía",
            "UDI - CFG",
            "Práctica Profesional Docente III",
        ]},
        {"anio": "4º año", "materias": [
            "Cálculo III",
            "Cálculo Numérico",
            "UDI - CFE",
            "Modelos Matemática",
            "Matemática Aplicada",
            "Física II",
            "Sociología de la Educación",
            "UDI - CFG",
            "Práctica Profesional Docente IV",
        ]},
    ],
    "Profesorado de Educación Secundaria en Química": [
        {"anio": "1º año", "materias": [
            "Biología General",
            "Química General",
            "Matemática",
            "Bioestadística",
            "Sujeto de la Educación",
            "Pedagogía",
            "Comprensión y Producción de Textos Académicos",
            "Formación Práctica Profesional I",
        ]},
        {"anio": "2º año", "materias": [
            "Química Orgánica",
            "Química Inorgánica",
            "Física General",
            "Ciencias de la Tierra",
            "Ecología",
            "Didáctica General",
            "Didáctica de las Ciencias Naturales",
            "Pensamiento Filosófico",
            "Sistema Educativo",
            "Formación Práctica Profesional II",
        ]},
        {"anio": "3º año", "materias": [
            "Química Biológica I",
            "Química Biológica II",
            "Fisicoquímica",
            "Química Analítica General",
            "Didáctica de la Química",
            "Psicología Educacional",
            "Educación para la Diversidad",
            "Gestión y Evaluación de los Aprendizajes",
            "Formación Práctica Profesional III",
        ]},
        {"anio": "4º año", "materias": [
            "Química Analítica Instrumental",
            "UDJE Formación Complementaria Específica",
            "Química Ambiental y de Salud",
            "Química de los Alimentos",
            "UDJE Historia y Patrimonio de Mendoza",
            "Educación y Tecnologías Digitales",
            "Educación Sexual Integral",
            "Formación Práctica Profesional IV",
        ]},
    ],
    "Profesorado de Educación Secundaria en Biología": [
        {"anio": "1º año", "materias": [
            "Biología General",
            "Química General",
            "Matemática",
            "Bioestadística",
            "Sujeto de la Educación",
            "Pedagogía",
            "Comprensión y Producción de Textos Académicos",
            "Formación Práctica Profesional I",
        ]},
        {"anio": "2º año", "materias": [
            "Química Orgánica",
            "Química Inorgánica",
            "Física General",
            "Ciencias de la Tierra",
            "Ecología",
            "Didáctica General",
            "Didáctica de las Ciencias Naturales",
            "Pensamiento Filosófico",
            "Sistema Educativo",
            "Formación Práctica Profesional II",
        ]},
        {"anio": "3º año", "materias": [
            "Didáctica de la Biología",
            "Biología Vegetal",
            "Biología Animal",
            "Microbiología y Biodiversidad",
            "Biología Humana",
            "Salud Humana",
            "Psicología Educacional",
            "Educación para la Diversidad",
            "Gestión y Evaluación de los Aprendizajes",
            "Formación Práctica Profesional III",
        ]},
        {"anio": "4º año", "materias": [
            "Química Biológica",
            "Genética",
            "Educación Ambiental",
            "UDJE Formación Complementaria Específica",
            "UDJE Historia y Patrimonio de Mendoza",
            "Educación y Tecnologías Digitales",
            "Educación Sexual Integral",
            "Formación Práctica Profesional IV",
        ]},
    ],
    "Tecnicatura en Producción Artística y Artesanal": [
        {"anio": "1º año", "materias": [
            "Historia del Arte I",
            "Técnicas Bidimensionales I",
            "Técnicas Tridimensionales I",
            "Dibujo y Diseño Proyectual I",
            "Tecnología de la Información y Comunicación",
            "Lenguaje Visual",
            "Técnicas y Prácticas Cerámicas I",
            "Comunicación, Comprensión y Producción de Textos",
            "Tecnología de los Materiales",
            "Práctica Profesionalizante I",
        ]},
        {"anio": "2º año", "materias": [
            "Historia del Arte II",
            "Técnicas Bidimensionales II",
            "Técnicas Tridimensionales II",
            "Dibujo y Diseño Proyectual II",
            "Tecnología Aplicada",
            "Inglés",
            "Técnicas y Prácticas Cerámicas II",
            "Diseño Cerámico",
            "Práctica Profesionalizante II",
        ]},
        {"anio": "3º año", "materias": [
            "Diseño de Productos",
            "Estructura de Costos",
            "Elaboración y Evaluación de Proyectos Productivos",
            "Marketing",
            "Cerámica",
            "Vitrofusión",
            "Esmaltado en Metales",
            "Patrimonio, Conservación y Restauración",
            "Problemática Sociocultural y el Contexto",
            "Práctica Profesionalizante III",
        ]},
    ],
    "Profesorado en Artes Visuales": [
        {"anio": "1º año", "materias": [
            "Dibujo I",
            "Bidimensión I",
            "Tridimensión I",
            "Lenguaje de las Artes Visuales I",
            "Historia de las Artes Visuales I",
            "Pedagogía",
            "Comprensión y Producción de Textos Académicos",
            "Formación Práctica Profesional I",
        ]},
        {"anio": "2º año", "materias": [
            "Dibujo II",
            "Bidimensión II",
            "Tridimensión II",
            "Lenguaje de las Artes Visuales II",
            "Historia de las Artes Visuales II",
            "Sujeto de la Educación I",
            "Didáctica de las Artes Visuales I",
            "Didáctica General",
            "Pensamiento Filosófico",
            "Sistema Educativo",
            "Formación Práctica Profesional II",
        ]},
        {"anio": "3º año", "materias": [
            "Producción Artística I: Bidimensión: Grabado - Pintura",
            "Producción Artística I: Tridimensión: Escultura - Cerámica",
            "Historia de las Artes Visuales III",
            "Dibujo III",
            "Lenguaje de las Artes Visuales III",
            "Didáctica de las Artes Visuales II",
            "Educación en la Diversidad",
            "Gestión y Evaluación de los Aprendizajes",
            "Psicología Educacional",
            "Formación Práctica Profesional III",
        ]},
        {"anio": "4º año", "materias": [
            "Información no disponible (no publicada por la institución)",
        ]},
    ],
    "Profesorado de Inglés": [
        {"anio": "1º año", "materias": [
            "Práctica Profesional Docente I",
            "Lengua Inglesa I",
            "Fonética y Fonología Inglesa I",
            "Gramática Inglesa I",
            "Prácticas de Lengua Inglesa",
            "Comprensión y Producción de Textos Académicos",
            "Pensamiento Filosófico",
            "Sistema Educativo",
            "Pedagogía",
        ]},
        {"anio": "2º año", "materias": [
            "Práctica Profesional Docente II",
            "Lengua Inglesa II",
            "Fonética y Fonología Inglesa II",
            "Gramática Inglesa II",
            "Didáctica del Inglés I",
            "Sujetos de la Educación I",
            "Sujetos de la Educación II",
            "Prácticas de Fonética y Fonología Inglesa",
            "Didáctica",
            "Instituciones Educativas",
            "Psicología Educacional",
        ]},
        {"anio": "3º año", "materias": [
            "Práctica Profesional Docente III",
            "Lengua Inglesa III",
            "Fonética y Fonología Inglesa III",
            "Gramática Inglesa III",
            "Didáctica del Inglés II",
            "Cultura y Literatura Británica I",
            "Cultura y Literatura Británica II",
            "Gestión y Evaluación de los Aprendizajes",
            "Proyectos de Intervención Socioeducativa",
            "Educación en la Diversidad",
        ]},
        {"anio": "4º año", "materias": [
            "Práctica Profesional Docente IV",
            "Lengua Inglesa IV",
            "U.D.J.E. (Unidad de Diseño Jurisdiccional Electiva)",
            "Fonética y Fonología Inglesa IV",
            "Formación Complementaria Específica",
            "Cultura y Literatura Norteamericana",
            "Historia y Patrimonio Cultural de Mendoza",
            "Formación Complementaria General",
            "Educación Sexual Integral",
            "Educación y Tecnologías Digitales",
        ]},
    ],
}


def main():
    dry = "--dry" in sys.argv
    ruta = os.path.join(DATA, "ies_godoycruz.json")
    with open(ruta, encoding="utf-8") as f:
        doc = json.load(f)
    asignadas = 0
    for inst in doc["instituciones"]:
        for c in inst.get("carreras", []):
            nombre = c["nombre_carrera"]
            if nombre in PLANES and not c.get("plan_estudio"):
                c["plan_estudio"] = PLANES[nombre]
                asignadas += 1
                n = sum(len(a["materias"]) for a in PLANES[nombre])
                print(f"   OK  {nombre[:52]:54} {len(PLANES[nombre])}a/{n}m")
    for nombre in PLANES:
        if not any(nombre == c["nombre_carrera"]
                   for i in doc["instituciones"] for c in i.get("carreras", [])):
            print(f"   ?? carrera no encontrada: {nombre}")
    if asignadas and not dry:
        with open(ruta, "w", encoding="utf-8") as f:
            json.dump(doc, f, ensure_ascii=False, indent=2)
            f.write("\n")
    print(f"### ies_godoycruz.json — {asignadas} asignadas{'  (DRY RUN)' if dry else ''}")


if __name__ == "__main__":
    main()
